# Generated by Django 5.2 on 2025-07-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
