# Generated by Django 5.2 on 2025-07-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_delete_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
